train:
  pred_dim: 1024
  root: "/data1/jjc/experiment" # g3/g4
  head_resume_path: "/data1/jjc/experiment/bi_tok/0526_janus_gen_1024/diff_head-bi_tok-100k"
  janus_resume_path: "/data1/jjc/experiment/bi_tok/0526_janus_gen_1024/janus-bi_tok-100k"
  skipped_keys:
  global_step: 100000
  exp_name: &exp_name "bi_tok"
  wandb_proj: *exp_name
  output_dir: "0527_janus_gen_1024_journeydb"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "wandb"
  
  lr: 1e-4
  num_iter: 200000
  save_every: 5000

data:
  name: "journeydb" # ["blip", "journeydb"]
  batch_size: 10
