janus_path: "/phd/jinjiachun/ckpt/deepseek-ai/Janus-Pro-1B"
decoder:
  type: "vit_pixel_decoder"
  hidden_size: 1024
  depth: 16
  num_heads: 16
  patch_size: 16
  grid_size: 24
  input_dim: 1024

rec_loss:
  perceptual_loss_name: "lpips-convnext_s-1.0-0.1"
  rec_weight: 1.0
  perceptual_weight: 1.1
  discriminator_weight: 0.1
  lecam_regularization_weight: 0.001

  discriminator_factor: 1.0
  discriminator_start_iter: 0

train:
  root: "/phd/jinjiachun/experiment"
  resume_path_decoder:
  resume_path_recloss:
  skipped_keys:
  global_step:
  exp_name: &exp_name "decoder"
  wandb_proj: *exp_name
  output_dir: "0618_vitdecoder"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "no"
  
  lr: 1e-4
  lr_disc: 1e-5
  num_iter: 500000
  save_every: 10000

data:
  name: "imagenet_wds"
  train_path: "/phd/jinjiachun/dataset/timm/imagenet-1k-wds"
  siglip_preprocess: false
  batch_size: 16
  num_workers: 4
  img_size: 384
